### ISSUE TITLE
Required Field Validator is ignored when inside a tabpanel

### ISSUE THREAD

**Issue by jcm4101** [DevExpress/AjaxControlToolkit#10] opened 2016-03-14 11:50 UTC
As described above, the required field validator doesn't fire when inside of a tabpanel

**Comment by MikhailTymchukDX** [comment] 2016-03-16 07:53
Do you mean that ValidatorCallout does not work inside the TabPanel, but Required Field Validator works?

**Comment by jcm4101** [comment] 2016-03-24 02:44
Yes, that is correct

**Comment by MikhailTymchukDX** [comment] 2016-03-24 08:43
TabPanel uses an UpdatePanel internally, so this issue seems to be a duplicate of the #21 issue.
Would you please check if the workaround described there applies to your scenario?

**Comment by MikhailTymchukDX** [comment] 2016-04-01 14:15
Closed due to inactivity.

**Closed by MikhailTymchukDX** 2016-04-01 14:15 UTC
