### ISSUE TITLE
AjaxControlToolkit LineChart

### ISSUE THREAD

**Issue by Saffarini** [DevExpress/AjaxControlToolkit#244] opened 2016-10-16 09:17 UTC
### The AJAX Control Toolkit <VERSION>

 15.1
### The installation method
-   NuGet package
### Minimal steps to reproduce the bug

```
When I tried to draw 2 series (A and B) to compare in the chart the 2nd series values is always equal the sum of A series values and B values.
```

for example :
 **A = 1 , 5 , 13 , 3 , 5 ,2**
 **B = 3 , 2 , 1 , 4 ,  3 , 6**
### Actual result

output drawing
 **A = 1 , 5 , 13 , 3 , 5 ,2**
 **B = 4 , 7 , 14 , 7 , 8 , 8** <-------
### Expected result

 **A = 1 , 5 , 13 , 3 , 5 ,2**
 **B = 3 , 2 , 1 , 4 ,  3 , 6**
### Browser(s) used
-  Chrome
-  Internet Explorer
### A site deployment method
-  VS development web-server,
### Code ASPX

```
    Protected Sub Compare(sender As Object, e As EventArgs)
        Dim query As String = String.Format("select datepart(year, orderdate) Year, count(datepart(year, orderdate)) TotalOrders from orders where shipcountry = '{0}' group by datepart(year, orderdate)", ddlCountry1.SelectedItem.Value)
        Dim dt As DataTable = GetData(query)

        Dim x As String() = New String(dt.Rows.Count - 1) {}
        Dim y As Decimal() = New Decimal(dt.Rows.Count - 1) {}
        For i As Integer = 0 To dt.Rows.Count - 1
            x(i) = dt.Rows(i)(0).ToString()
            y(i) = Convert.ToInt32(dt.Rows(i)(1))
        Next
        LineChart1.Series.Add(New AjaxControlToolkit.LineChartSeries() With {
         .Name = ddlCountry1.SelectedItem.Value,
         .Data = y
        })

        query = String.Format("select datepart(year, orderdate) Year, count(datepart(year, orderdate)) TotalOrders from orders where shipcountry = '{0}' group by datepart(year, orderdate)", ddlCountry2.SelectedItem.Value)
        dt = GetData(query)

        y = New Decimal(dt.Rows.Count - 1) {}
        For i As Integer = 0 To dt.Rows.Count - 1
            x(i) = dt.Rows(i)(0).ToString()
            y(i) = Convert.ToInt32(dt.Rows(i)(1))
        Next
        LineChart1.Series.Add(New AjaxControlToolkit.LineChartSeries() With {
         .Name = ddlCountry2.SelectedItem.Value,
         .Data = y
        })
        LineChart1.CategoriesAxis = String.Join(",", x)

        LineChart1.ChartTitle = String.Format("{0} and {1} Order Distribution", ddlCountry1.SelectedItem.Value, ddlCountry2.SelectedItem.Value)
        LineChart1.Visible = True
    End Sub
```

**Comment by MikhailTymchukDX** [comment] 2016-10-17 11:58
Hi @Saffarini ,
We were unable to reproduce this issue.
Would you please check data that the `GetData()` method returns or provide a complete sample project to research?

**Comment by MikhailTymchukDX** [comment] 2016-10-31 08:57
Since we still haven't received the requested information, I'm closing this issue.
Feel free to reopen it once you have any additional info regarding the error.

**Closed by MikhailTymchukDX** 2016-10-31 08:57 UTC
Labels: LineChart, needs info
