### ISSUE TITLE
Method 'System.Web.UI.ScriptManager.get_EnableCdn' not found.

### ISSUE THREAD

**Issue by Scothosts** [DevExpress/AjaxControlToolkit#415] opened 2018-02-23 13:06 UTC
I am moving from Windows running VS2012 Pro to Mac running VS2017 Pro and although I have updated .Net to 4.6.2 and using the latest ajaxcontroltoolkit I cannot fix this error. I have googled and cannot source any resolution. Please help as I am really stuck.

**Comment by MikhailTymchukDX** [comment] 2018-02-26 07:57
Hi @Scothosts 
I cannot reproduce this behavior.
Would you please provide a sample project that illustrates this issue?

**Comment by Scothosts** [comment] 2018-02-26 12:04
I have the asp:scriptmanager, a textbox and the htmleditorextender and every time I run my asps page on Mac vs2017 I get the error above.

I believe it maybe an issue with mono and it being on Mac. Can you confirm?

**Comment by MikhailTymchukDX** [comment] 2018-02-27 10:49
Hi @Scothosts 

Adding the following line to the Default.aspx page of the default ASP.NET Web Forms project template in Visual Studio on Mac makes an application fail to start:

```aspx
<asp:ScriptManager runat="server" EnableCdn="false" />
```
It throws `System.Web.Compilation.ParseException`:
```
Details: Unrecognized attribute: EnableCdn
```

The project does not contain any AJAX Control Toolkit reference at this point, so this is not the tooolkit issue.
Because of that, I will close this issue until we have a confirmation that this issue is related to the toolkit.

**Closed by MikhailTymchukDX** 2018-02-27 10:49 UTC
Labels: needs info
