### ISSUE TITLE
Cascadingdropdown fires onchange event on load

### ISSUE THREAD

**Issue by VKB2612** [DevExpress/AjaxControlToolkit#516] opened 2019-12-20 13:39 UTC
Hi,

The parent dropdown change/load of child dropdown triggers change event of child dropdown. This issue occurs only in new version of Firefox. 

The AJAX Control Toolkit version 19.1.0.0

### The installation method
- [x] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

Please refer the attached project and video for more details. On load of cities dropdown fires change event setParams() only in Firefox.

### Actual result
change event fires on load of dropdown

### Expected result
change event should be triggered only on select event of this dropdown

### Browser(s) used
Firefox version 71.0 (64-Bit)
IE 11

### A site deployment method
- [ ] VS development web-server,
- [x ] IIS

Also, I am not able to upload project files or video showing error though the zip file size is 8MB. So, I writing the code here.

aspx:

            <asp:ScriptManager ID="ScriptManager1" runat="server" EnablePartialRendering="True" />
            <table border="0">
		        <tr>
		            <td>Country:</td>
		            <td>
			            <asp:DropDownList ID="AJAX_DDL_COUNTRY" runat="server"></asp:DropDownList>
		        		<ajaxToolkit:CascadingDropDown 
                            ID="CascadingDropDownCO"
                            runat="server"
                            TargetControlID="AJAX_DDL_COUNTRY"
                            Category="CO"
                            LoadingText="Loading ..."
                            ServicePath="WebService1.asmx"
                            ServiceMethod="GetCountries"
                            UseContextKey="true"
                            />
                    </td>
		        </tr>
		        <tr>
		            <td>City:</td>
		            <td>
			            <asp:DropDownList ID="AJAX_DDL_CITIES" runat="server"></asp:DropDownList>
                        <ajaxToolkit:CascadingDropDown 
                            ID="CascadingDropDownCI"
                            runat="server"
                            TargetControlID="AJAX_DDL_CITIES"
                            ParentControlID="AJAX_DDL_COUNTRY"
                            Category="CI"
                            LoadingText="Loading ..."
                            ServicePath="WebService1.asmx"
                            ServiceMethod="GetCities"
                            UseContextKey="true" />
                    </td>
                </tr>
                </table>

aspx.cs:

    public partial class CascadingDDL_Test : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void Page_Init(object sender, EventArgs e)
        {
            AJAX_DDL_CITIES.Attributes["onchange"] = "setParams()";
        }
    }

web service for cascading dropdowns:

/// <summary>
    /// Summary description for WebService1
    /// </summary>
    [WebService(Namespace = "http://tempuri.org/")]
    [WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]
    [System.ComponentModel.ToolboxItem(false)]
    // To allow this Web Service to be called from script, using ASP.NET AJAX, uncomment the following line. 
    [System.Web.Script.Services.ScriptService]
    public class WebService1 : System.Web.Services.WebService
    {
        List<CascadingDropDownNameValue> values;

        [WebMethod]
        public CascadingDropDownNameValue[] GetCountries(string contextKey)
        {
            values = new List<CascadingDropDownNameValue>();
            values.Add(new CascadingDropDownNameValue("Please select", "Please select"));
            values.Add(new CascadingDropDownNameValue("USA", "USA"));
            values.Add(new CascadingDropDownNameValue("Germany", "Germany"));
            return values.ToArray();
        }

        [WebMethod]
        public CascadingDropDownNameValue[] GetCities(
        string knownCategoryValues,
        string category,
        string contextKey)
        {

            System.Collections.Specialized.StringDictionary kv = CascadingDropDown.ParseKnownCategoryValuesString(knownCategoryValues);
            string country = (kv.ContainsKey("CO")) ? kv["CO"].ToString() : string.Empty;

            values = new List<CascadingDropDownNameValue>();
            if (string.IsNullOrEmpty(country) || country.Equals("Please select"))
            {
                return null;
            }

            switch(country)
            {
                case "USA":
                    values.Add(new CascadingDropDownNameValue("NEWYORK", "NEWYORK"));
                    values.Add(new CascadingDropDownNameValue("SAN JOSE", "SAN JOSE"));
                    break;

                case "Germany":
                    values.Add(new CascadingDropDownNameValue("BERLIN", "BERLIN"));
                    values.Add(new CascadingDropDownNameValue("FRANKFURT", "FRANKFURT"));
                    break;
            }
            return values.ToArray();
        }//GetAreas
    }

Though it seems like a simple error, this is affecting the application in LIVE environment. 
Please help.

Regards

**Comment by AlekseyMartynov** [comment] 2019-12-23 12:26
Duplicate of #477.
Please [upgrade to the latest `master` build](https://github.com/DevExpress/AjaxControlToolkit/wiki/Updating-the-Project-from-CI-Builds).

**Closed by AlekseyMartynov** 2019-12-23 12:26 UTC
