### ISSUE TITLE
Error upload file  with  AjaxFileUpload

### ISSUE THREAD

**Issue by mandolfo** [DevExpress/AjaxControlToolkit#396] opened 2017-11-13 09:40 UTC
### The AJAX Control Toolkit \<VERSION\>
Version 17.1.1

### The installation method
- [ x ] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
A web application use the AjaxFileUpload component to upload file. The application use Asp.Net 4.5 under IIS7 with integrated mode application pool

When try to upload file there is an exception from AjaxFileUploadHandler.axd

URL:https://portalenew.inteddy.it:8443/PeopleNetTest/AjaxFileUploadHandler.axd?contextKey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&controlID=ContentPlaceHolder1_AjaxFileUpload&fileId=2479A608-9CAF-B2E2-04DE-741F16FE562A&fileName=CV_EBC 26013   TEST.docx&chunked=false&firstChunk=true

This method or property is not supported after HttpRequest.Form, Files, InputStream, or BinaryRead has been invoked.

Stack Trace :   at System.Web.HttpRequest.GetInputStream(Boolean persistEntityBody, Boolean disableMaxRequestLength)
   at AjaxControlToolkit.AjaxFileUploadHelper.Process(HttpContext context)
   at AjaxControlToolkit.AjaxFileUploadHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Under IIS 8 the upload control works 

### Actual result
Exception 

### Expected result
upload file 

### Browser(s) used
Chrome , Edge,Firefox

### A site deployment method
- [ ] VS development web-server,
- [x] IIS7

This is the setup of the component

[ASPX]

<asp:AjaxFileUpload ID="AjaxFileUpload" runat="server" AutoStartUpload="true" Font-Names="Lato" ClearFileListAfterUpload="true"   OnUploadComplete="AjaxFileUpload_UploadComplete"
 MaximumNumberOfFiles="1" MaxFileSize="2048" Mode="Auto" OnClientUploadComplete="uploadComplete"
Width="100%" />
                    
 [C#]

 protected void AjaxFileUpload_UploadComplete(object sender, AjaxControlToolkit.AjaxFileUploadEventArgs e)
        {
            e.PostedUrl = SavePostedFile2(e.FileName,e.GetContents(),0,e.GetStreamContents());
        }

  protected string SavePostedFile2(string filename,byte[] fileByte, int modo,Stream stream)
        {

            string myString = GenerateCausale(10);
            string _extension = "." + filename.Split('.')[filename.Split('.').Count() - 1];

           UploadFileH1Web _upload = new UploadFileH1Web();

            string _codiceFile = _upload.calcolaCodiceEstensioneFile(stream);
            string _codicePrevisto = _upload.verificaCodiceEstensioneFile(_extension).ToString();

            if (_codiceFile != _codicePrevisto)
                return string.Empty;

            string fileName = "";

             // the upload file fails here
             AjaxFileUpload.SaveAs(Server.MapPath("Documenti/" + myString + "." + _extension));
             fileName = "Documenti/" + myString + "." + _extension;
            

            return fileName;

        }

[JS]

function uploadComplete(sender,e) {

        var _risposta = e.get_postedUrl();
     
        

    }

[web.config]

<handlers>

      <add name="AjaxFileUploadHandler" verb="*"
           path="AjaxFileUploadHandler.axd"
           type="AjaxControlToolkit.AjaxFileUploadHandler, 
          AjaxControlToolkit"/>
    </handlers>

**Comment by MikhailTymchukDX** [comment] 2017-11-13 11:45
Hi @mandolfo 

I simplified your code so that it can be run out of the box: [GetInputStreamTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1466645/GetInputStreamTest.zip)
However, I have no problems with it on IIS 7.

Do you see the same error when running this project on IIS 7 in your environment?

Also, please take a look at this issue which seems to be related to yours: https://github.com/DevExpress/AjaxControlToolkit/issues/111.

**Comment by mandolfo** [comment] 2017-11-13 16:10
The web application   uses a CAS Authentication with DotNetCasClient component

We removed the CAS Login and CAS configuration from the web.config and  upload  file works…  but  DotNetCasClient is required.

How can we solve this issue ? We have to upload file under CAS Authentication

Marco Andolfo

[Descrizione: Descrizione: Logo EBC 31]
Via Antonio Canova, 16/20 40138 Bologna
Tel. +39 051 5881511
www.ebcconsulting.com

Le informazioni contenute nella presente comunicazione e i relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente alle persone o alla Società sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi dell’art. 616 c.p. , che ai sensi del D.Lgs. n. 196/2003.
Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di informarci immediatamente per telefono o inviando un messaggio all’indirizzo e-mail mandolfo@ebcconsulting.com<mailto:mandolfo@ebcconsulting.com>


Da: MikhailTymchukDX [mailto:notifications@github.com]
Inviato: lunedì 13 novembre 2017 12:45
A: DevExpress/AjaxControlToolkit
Cc: Marco Andolfo; Mention
Oggetto: Re: [DevExpress/AjaxControlToolkit] Error upload file with AjaxFileUpload (#396)


Hi @mandolfo<https://github.com/mandolfo>

I simplified your code so that it can be run out of the box: GetInputStreamTest.zip<https://github.com/DevExpress/AjaxControlToolkit/files/1466645/GetInputStreamTest.zip>
However, I have no problems with it on IIS 7.

Do you see the same error when running this project on IIS 7 in your environment?

Also, please take a look at this issue which seems to be related to yours: #111<https://github.com/DevExpress/AjaxControlToolkit/issues/111>.

**Comment by MikhailTymchukDX** [comment] 2017-11-13 17:43
You can try [this approach](https://forums.asp.net/login/RedirectToLogin?ReturnUrl=/post/set/25/1859232/5228653):

1. Create a new HttpModule that forces input stream to be bufferless.
```cs
public class BufferlessInputStreamWorkaroundModule : IHttpModule {
  public void Dispose() {
  }

  public void Init(HttpApplication context) {
    context.BeginRequest += context_BeginRequest;
  }

  void context_BeginRequest(object sender, EventArgs e) {
    if((sender as HttpApplication).Request.ReadEntityBodyMode != ReadEntityBodyMode.Bufferless) {
      var stream = (sender as HttpApplication).Request.GetBufferlessInputStream(true);
    }
  }
}
```
2. Register this module in Web.config **before any other module**:
```xml
<system.webServer>
  <modules>
    <add name="BufferlessInputStreamWorkaroundModule" type="GetInputStreamTest.BufferlessInputStreamWorkaroundModule, GetInputStreamTest"  />
  ...
  <modules>
</system.webServer>
```

I updated my sample project so you can check this in action: [GetInputStreamTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1467836/GetInputStreamTest.zip)

**Comment by mandolfo** [comment] 2017-11-14 17:49
After created the workaround  the issue still remains

Here the web.config

<configuration>
                <configSections>
                               
                               <section name="casClientConfig" type="DotNetCasClient.Configuration.CasClientConfiguration, DotNetCasClient" />
                               <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
                               <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
                                               <section name="H1Web.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
                               </sectionGroup>
                               <sectionGroup name="devExpress">
                                               <section name="themes" type="DevExpress.Web.ASPxClasses.ThemesConfigurationSection, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" requirePermission="false" />
                                               <section name="compression" type="DevExpress.Web.ASPxClasses.CompressionConfigurationSection, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" requirePermission="false" />
                                               <section name="settings" type="DevExpress.Web.ASPxClasses.SettingsConfigurationSection, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" requirePermission="false" />
                                               <section name="errors" type="DevExpress.Web.ASPxClasses.ErrorsConfigurationSection, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" requirePermission="false" />
                               </sectionGroup>
                </configSections>
                <appSettings>
                               <add key="DefaultLanguage" value="1" />





                               </appSettings>
                <connectionStrings>
                               </connectionStrings>
                <casClientConfig casServerLoginUrl="https://portalenew.inteddy.it/cas/login" casServerUrlPrefix="https://portalenew.inteddy.it/cas/" serverName="https://portalenew.inteddy.it/PeopleNetTest/" ticketValidatorName="Cas20" redirectAfterValidation="true" serviceTicketManager="CacheServiceTicketManager" renew="false" gatewayStatusCookieName="cas_gateway_status" singleSignOut="true"/>

                <system.web>

                <customErrors mode="Off" />
                               <compilation targetFramework="4.5">

                                               <assemblies>
                                                               <add assembly="DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="DevExpress.Data.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="DevExpress.Printing.v13.1.Core, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
                                                               <add assembly="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
                                                               <add assembly="DevExpress.RichEdit.v13.1.Core, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="System.Data.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
                                                               <add assembly="DevExpress.Web.ASPxThemes.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
                                                               <add assembly="DevExpress.Web.ASPxHtmlEditor.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="DevExpress.Web.ASPxSpellChecker.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="DevExpress.Office.v13.1.Core, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="DevExpress.SpellChecker.v13.1.Core, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="System.Web.Extensions.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
                                                               <add assembly="DevExpress.XtraCharts.v13.1.Web, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="DevExpress.XtraCharts.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="DevExpress.Charts.v13.1.Core, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />
                                                               <add assembly="DevExpress.Utils.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A" />

                                               </assemblies>
                               </compilation>
                               <httpRuntime targetFramework="4.5" />
                               <pages>
                                               <namespaces />
                                               <controls>
                                                               <add assembly="Microsoft.AspNet.Web.Optimization.WebForms" namespace="Microsoft.AspNet.Web.Optimization.WebForms" tagPrefix="webopt" />
                                                               <add tagPrefix="ajaxToolkit" assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" />
                                               </controls>
                               </pages>
                               <authentication mode="Forms">
                                               <forms loginUrl="https://portalenew.inteddy.it/cas/login" timeout="30" cookieless="UseCookies" path="/PeopleNetTest" defaultUrl="~/GestoreAutenticazione.aspx"  />
                               </authentication>
    <authorization>
      <deny users="?" />
    </authorization>
                               <profile defaultProvider="DefaultProfileProvider">
                                               <providers>
                                                               <add name="DefaultProfileProvider" type="System.Web.Providers.DefaultProfileProvider, System.Web.Providers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" connectionStringName="DefaultConnection" applicationName="/" />
                                               </providers>
                               </profile>
                               <membership defaultProvider="DefaultMembershipProvider">
                                               <providers>
                                                               <add name="DefaultMembershipProvider" type="System.Web.Providers.DefaultMembershipProvider, System.Web.Providers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" connectionStringName="DefaultConnection" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" requiresUniqueEmail="false" maxInvalidPasswordAttempts="5" minRequiredPasswordLength="6" minRequiredNonalphanumericCharacters="0" passwordAttemptWindow="10" applicationName="/" />
                                               </providers>
                               </membership>
                               <roleManager defaultProvider="DefaultRoleProvider">
                                               <providers>
                                                               <add name="DefaultRoleProvider" type="System.Web.Providers.DefaultRoleProvider, System.Web.Providers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" connectionStringName="DefaultConnection" applicationName="/" />
                                               </providers>
                               </roleManager>
                               
                               <sessionState timeout="999" mode="InProc" customProvider="DefaultSessionProvider">
                                               <providers>
                                                               <add name="DefaultSessionProvider" type="System.Web.Providers.DefaultSessionStateProvider, System.Web.Providers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" connectionStringName="DefaultConnection" />
                                               </providers>
                               </sessionState>
                               <httpModules>
                               <add name="DotNetCasClient" type="DotNetCasClient.CasAuthenticationModule,DotNetCasClient" />
                                               <add type="DevExpress.Web.ASPxClasses.ASPxHttpHandlerModule, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" name="ASPxHttpHandlerModule" />
                               </httpModules>
                <httpHandlers>
                                               <add type="DevExpress.Web.ASPxClasses.ASPxHttpHandlerModule, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" verb="GET" path="DX.ashx" validate="false" />
                                               <add type="DevExpress.Web.ASPxUploadControl.ASPxUploadProgressHttpHandler, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" verb="GET,POST" path="ASPxUploadProgressHandlerPage.ashx" validate="false" />
                               <add verb="*" path="DocumentHandler.axd" type="Gnostice.Documents.WebHandler.DocumentHandler, Gnostice.Documents.WebHandler" />
                               <add verb="*" path="AjaxFileUploadHandler.axd" type="AjaxControlToolkit.AjaxFileUploadHandler, AjaxControlToolkit"/>
                               </httpHandlers>
<trace enabled="true" requestLimit="50" pageOutput="false" traceMode="SortByTime" localOnly="false" />


                </system.web>
                <runtime>
                               <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
                                               <dependentAssembly>
                                                               <assemblyIdentity name="DotNetOpenAuth.Core" publicKeyToken="2780ccd10d57b246" />
                                                               <bindingRedirect oldVersion="1.0.0.0-4.0.0.0" newVersion="4.1.0.0" />
                                               </dependentAssembly>
                                               <dependentAssembly>
                                                               <assemblyIdentity name="DotNetOpenAuth.AspNet" publicKeyToken="2780ccd10d57b246" />
                                                               <bindingRedirect oldVersion="1.0.0.0-4.0.0.0" newVersion="4.1.0.0" />

                                               </dependentAssembly>
                                               <dependentAssembly>
                                                               <assemblyIdentity name="Gnostice.XtremeFontEngine.4.0" publicKeyToken="461de9da64be3a84" culture="neutral" />
                                                               <bindingRedirect oldVersion="0.0.0.0-1.0.1810.392" newVersion="1.0.1809.392" />
                                               </dependentAssembly>
                                               <dependentAssembly>
                                                               <assemblyIdentity name="Gnostice.XtremeImageEngine" publicKeyToken="67e9a3a7c22f1690" culture="neutral" />
                                                               <bindingRedirect oldVersion="0.0.0.0-12.0.1511.103" newVersion="12.0.1510.103" />
                                               </dependentAssembly>
                                                               <dependentAssembly>
                                                               <assemblyIdentity name="Gnostice.Core" publicKeyToken="fc8cb3ab6a24df63" culture="neutral" />
                                                               <bindingRedirect oldVersion="0.0.0.0-17.4.0.0" newVersion="17.4.0.0" />




                                               </dependentAssembly>

                                               <dependentAssembly>
                                                               <assemblyIdentity name="Gnostice.Documents" publicKeyToken="fc8cb3ab6a24df63" culture="neutral" />
                                                               <bindingRedirect oldVersion="0.0.0.0-17.4.0.0" newVersion="17.4.0.0" />
                                               </dependentAssembly>
                               </assemblyBinding>
                </runtime>
                <entityFramework>
                               <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
                                               <parameters>
                                                               <parameter value="v11.0" />
                                               </parameters>
                               </defaultConnectionFactory>
                </entityFramework>
                <system.webServer>
                <staticContent>
      <remove fileExtension=".woff" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".woff2" mimeType="font/x-woff" />
   </staticContent>
                <validation validateIntegratedModeConfiguration="false" />
                               <modules>
<add name="BufferlessInputStreamWorkaroundModule" type="H1Web.BufferlessInputStreamWorkaroundModule, H1Web"  />

                               <remove name="DotNetCasClient" />
            <add name="DotNetCasClient" type="DotNetCasClient.CasAuthenticationModule,DotNetCasClient" />
                                               <add type="DevExpress.Web.ASPxClasses.ASPxHttpHandlerModule, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" name="ASPxHttpHandlerModule" />
                               </modules>

                                               <handlers>

                                               <add type="DevExpress.Web.ASPxClasses.ASPxHttpHandlerModule, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" verb="GET" path="DX.ashx" name="ASPxHttpHandlerModule" preCondition="integratedMode" />
                                               <add type="DevExpress.Web.ASPxUploadControl.ASPxUploadProgressHttpHandler, DevExpress.Web.v13.1, Version=13.1.8.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" verb="GET,POST" path="ASPxUploadProgressHandlerPage.ashx" name="ASPxUploadProgressHandler" preCondition="integratedMode" />
                               <add name="XDocumentImage" verb="*" path="DocumentHandler.axd" type="Gnostice.Documents.WebHandler.DocumentHandler, Gnostice.Documents.WebHandler" />
   <add name="AjaxFileUploadHandler" verb="*"
           path="AjaxFileUploadHandler.axd"
           type="AjaxControlToolkit.AjaxFileUploadHandler,
          AjaxControlToolkit"/>
                               </handlers>
        <security>
            <requestFiltering>
                <requestLimits maxAllowedContentLength="1000000" />
            </requestFiltering>
        </security>
        <defaultDocument>
            <files>
                <clear />
                <add value="GestoreAutenticazione.aspx" />
            </files>
        </defaultDocument>
                </system.webServer>
                <devExpress>
                               <themes enableThemesAssembly="true" styleSheetTheme="" theme="" customThemeAssemblies="" />
                               <compression enableHtmlCompression="false" enableCallbackCompression="true" enableResourceCompression="true" enableResourceMerging="true" />
                               <settings doctypeMode="Xhtml" rightToLeft="false" />
                               <errors callbackErrorRedirectUrl="" />
                </devExpress>
                <applicationSettings>
 </applicationSettings>

                <system.diagnostics>
  <trace autoflush="true" useGlobalLock="false" />
  <sharedListeners>
    
    <add name="TraceFile"
         type="System.Diagnostics.TextWriterTraceListener"
         initializeData="C:\inetpub\wwwroot\H1Web\PeopleNetTest\log\DotNetCasClient.Log"
         traceOutputOptions="DateTime" />
  </sharedListeners>
  <sources>
    
    <source name="DotNetCasClient.Config" switchName="Config" switchType="System.Diagnostics.SourceSwitch" >
      <listeners>
        <add name="TraceFile" />
      </listeners>
    </source>
    
    <source name="DotNetCasClient.HttpModule" switchName="HttpModule" switchType="System.Diagnostics.SourceSwitch" >
      <listeners>
        <add name="TraceFile" />
      </listeners>
    </source>
    
    <source name="DotNetCasClient.Protocol" switchName="Protocol" switchType="System.Diagnostics.SourceSwitch" >
      <listeners>
        <add name="TraceFile" />
      </listeners>
    </source>
    
    <source name="DotNetCasClient.Security" switchName="Security" switchType="System.Diagnostics.SourceSwitch" >
      <listeners>
        <add name="TraceFile" />
      </listeners>
    </source>
  </sources>
  <switches>
    
    
    <add name="Config" value="Information"/>
    
    <add name="HttpModule" value="Information"/>
    
    <add name="Protocol" value="Verbose"/>
    
    <add name="Security" value="Information"/>
  </switches>
</system.diagnostics>
<system.web.extensions>
    <scripting>
      <webServices>
        <jsonSerialization maxJsonLength="2147483644"></jsonSerialization>
      </webServices>
    </scripting>
  </system.web.extensions>

</configuration>

The class BufferlessInputStreamWorkaroundModule

using System;
using System.Web;

namespace H1Web
{
    public class BufferlessInputStreamWorkaroundModule : IHttpModule
    {
        /// <summary>
        /// Il modulo dovrà essere configurato nel file Web.config del
        /// Web e registrato con IIS prima di poter essere utilizzato. Per ulteriori informazioni
        /// visitare il sito all'indirizzo: http://go.microsoft.com/?linkid=8101007
        /// </summary>
        #region IHttpModule Members

        public void Dispose()
        {
            //Inserire qui il codice di pulizia.
        }

        public void Init(HttpApplication context)
        {
            // Segue un esempio di come gestire l'evento LogRequest e fornire la relativa
            // implementazione della registrazione personalizzata
            context.LogRequest += new EventHandler(OnLogRequest);
        }

        #endregion

        public void OnLogRequest(Object source, EventArgs e)
        {
            //La logica della registrazione personalizzata può essere inserita qui
        }

        void context_BeginRequest(object sender, EventArgs e)
        {
            if ((sender as HttpApplication).Request.ReadEntityBodyMode != ReadEntityBodyMode.Bufferless)
            {
                var stream = (sender as HttpApplication).Request.GetBufferlessInputStream(true);
            }
        }
    }
}



Da: MikhailTymchukDX [mailto:notifications@github.com]
Inviato: lunedì 13 novembre 2017 18:44
A: DevExpress/AjaxControlToolkit
Cc: Marco Andolfo; Mention
Oggetto: Re: [DevExpress/AjaxControlToolkit] Error upload file with AjaxFileUpload (#396)


You can try this approach<https://forums.asp.net/login/RedirectToLogin?ReturnUrl=/post/set/25/1859232/5228653>:

  1.  Create a new HttpModule that forces input stream to be bufferless.

public class BufferlessInputStreamWorkaroundModule : IHttpModule {

  public void Dispose() {

  }



  public void Init(HttpApplication context) {

    context.BeginRequest += context_BeginRequest;

  }



  void context_BeginRequest(object sender, EventArgs e) {

    if((sender as HttpApplication).Request.ReadEntityBodyMode != ReadEntityBodyMode.Bufferless) {

      var stream = (sender as HttpApplication).Request.GetBufferlessInputStream(true);

    }

  }

}

  1.  Register this module in Web.config before any other module:

<system.webServer>

  <modules>

    <add name="BufferlessInputStreamWorkaroundModule" type="GetInputStreamTest.BufferlessInputStreamWorkaroundModule, GetInputStreamTest"  />

  ...

  <modules>

</system.webServer>

I updated my sample project so you can check this in action: GetInputStreamTest.zip<https://github.com/DevExpress/AjaxControlToolkit/files/1467836/GetInputStreamTest.zip>

**Comment by MikhailTymchukDX** [comment] 2017-11-15 10:50
Hi @mandolfo 
Your `IHttpModule` implementation is incorrect.

The `Init` method should be the following:
```cs
public void Init(HttpApplication context) {
    context.BeginRequest += context_BeginRequest;
}
```

**Comment by mandolfo** [comment] 2017-11-16 14:19
Sorry but we have another problems.

The web application uses some general variables. Variables are saved in Session Object (we can’t save them into the web.config) but if we load the module the Session Object is null and we can’t use the application

Some solutions ?

Da: MikhailTymchukDX [mailto:notifications@github.com]
Inviato: mercoledì 15 novembre 2017 11:51
A: DevExpress/AjaxControlToolkit
Cc: Marco Andolfo; Mention
Oggetto: Re: [DevExpress/AjaxControlToolkit] Error upload file with AjaxFileUpload (#396)


Hi @mandolfo<https://github.com/mandolfo>
Your IHttpModule implementation is incorrect.

The Init method should be the following:

public void Init(HttpApplication context) {

    context.BeginRequest += context_BeginRequest;

}

**Comment by MikhailTymchukDX** [comment] 2017-11-16 15:58
Hi @mandolfo 
I could not reproduce this behavior in my test project.
Would you please modify the project I attached earlier to demonstrate this issue?

**Comment by MikhailTymchukDX** [comment] 2017-12-01 09:25
@mandolfo 
Since we still haven't received the requested information, I'm closing this issue.
Once you have any additional info regarding the error, please notify us by adding a comment.

**Closed by MikhailTymchukDX** 2017-12-01 09:25 UTC
Labels: AjaxFileUpload, needs info

**Comment by MikhailTymchukDX** [comment] 2018-04-03 13:05
We reproduced the problem and added the property `useBufferlessInputStream` in the context of PR #428.
The latest build is available at [AppVeyor](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/artifacts).

To use the control with the Classic ReadEntityBodyMode, add the `useBufferlessInputStream` property to the `ajaxControlToolkit` section of Web.config and set it to `false`:
```xml
<configuration>
  <configSections>
    <section name="ajaxControlToolkit" type="AjaxControlToolkit.AjaxControlToolkitConfigSection, AjaxControlToolkit" requirePermission="false"/>
  </configSections>
  <ajaxControlToolkit useBufferlessInputStream="false" />
</configuration>
```

**Comment by MikhailTymchukDX** [comment] 2018-04-05 08:19
We changed the approach introduced in PR #428 to more flexible solution in the context of PR #429.
AjaxFileUpload detects stream mode automatically, the `useBufferlessInputStream` property is removed.
