### ISSUE TITLE
IE 11 doesn't support the 'attachevent'

### ISSUE THREAD

**Issue by xiaoaowanghu** [DevExpress/AjaxControlToolkit#316] opened 2017-03-22 06:27 UTC
### The AJAX Control Toolkit \<VERSION\>
v16.1.1
### The installation method
- [*] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Actual result

I don't know where call the MicrosoftAjaxWebForms.js but when execute a function in my page. Then the IE 11 browser will popup a error message in the console :
_SCRIPT438: Object doesn't support property or method 'attachEvent'
ScriptResource.axd (2,27330)_

And the ScriptResource.axd (2,27330) should be MicrosoftAjaxWebForms.js. I check the code, it indeed have called 'attachevent' in MicrosoftAjaxWebForms.js

### Browser(s) used
IE11.953.14393.0

### A site deployment method
- [ ] VS development web-server,
- [* ] IIS

**Comment by MikhailTymchukDX** [comment] 2017-03-22 09:04
@xiaoaowanghu Your scenario is not entirely clear to me.
Would you please provide a sample project that illustrates this issue?

**Comment by KMounikaPrasad** [comment] 2018-01-19 07:28
Hi MikhailTymchukDX,

I have exactly the same problem using my application on IE11-
AjaxToolkit 4.0
ASP.Net 4.0
.Net Framework 4.5
jquery 1.3.2

Could you please help?

Thanks,
Mounika.

**Comment by MikhailTymchukDX** [comment] 2018-01-19 07:42
Hi @KMounikaPrasad 
Since we could not reproduce the problem, would you please provide us with a sample project that illustrates this issue?

**Comment by KMounikaPrasad** [comment] 2018-01-19 09:12
Hi MikhailTymchukDX,

Thanks for your quick response.
I shall provide you with a sample project to see the issue. 

Thanks,
Mounika.

**Comment by mounikapk** [comment] 2018-01-25 07:44
Hi MikhailTymchukDX,

We are now upgrading AjaxcontrolToolkit to the current latest version.  Can you help me with which is the most latest and stable one. From NuGet package in VS2017, i am seeing 18.0. Is it ok to use?

Thanks,
Mounika.

**Comment by MikhailTymchukDX** [comment] 2018-01-25 07:54
@mounikapk Yes, this is the most stable version.

**Comment by mounikapk** [comment] 2018-01-25 07:58
Ok. Also, which would be the JQuery version  that works for Ajax18.0?

**Comment by MikhailTymchukDX** [comment] 2018-01-26 16:05
@mounikapk The AJAX Control Toolkit does not depend on jQuery nor we test the compatibility with any jQuery version, so you can choose any.
If you have further questions, please file a separate issue to stay focused on initial problem in this thread.

**Comment by MikhailTymchukDX** [comment] 2018-02-12 16:46
Since we still haven't received the requested information, I'm closing this issue.
Once you have any additional info regarding the error, please notify us by adding a comment.

**Closed by MikhailTymchukDX** 2018-02-12 16:46 UTC
Labels: needs info
