### ISSUE TITLE
With free you get crap...

### ISSUE THREAD

**Issue by BKCantor** [DevExpress/AjaxControlToolkit#277] opened 2016-12-10 21:13 UTC
### The installation method
- [X] Installer
- [X] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
Install the damned thing.

### Actual result
exceeding fooBar
### Expected result
the damned thing to work
### Browser(s) used
IE10, Chrome 
### A site deployment method
- [ X] VS development web-server,

Really? Adding "OnClientActiveTabChanged" to ajaxToolkit:TabContainer causes the entire page to go freakin' blank and everything has it's style set to visibility:hidden?

And, no, the fix for the TabContainer where the tab content shows to the right vs. beneath the tabs does not work.

I show the AjaxToolkit Demo page to customers, they pick/choose features, I download the installer and add it to their solution, then add the features they want, deploy it to test or production, and everything goes to shitsville.

Man, this is a piece of crap.

**Comment by MikhailTymchukDX** [comment] 2016-12-12 11:16
Hi @BKCantor ,
We could not reproduce this behavior.
I attached a sample project that works correctly when `OnClientActiveTabChanged` is added: 
[TabsOnClientActiveTabChanged.zip](https://github.com/DevExpress/AjaxControlToolkit/files/645743/TabsOnClientActiveTabChanged.zip)

Would you please update this project or provide your own project to illustrate the described issue?

Also, it will be very helpful to provide us with a separate sample project that illustrates the problem with the tab content positioning.

**Comment by MikhailTymchukDX** [comment] 2016-12-24 19:46
Since we still haven't received the requested information, I'm closing this issue.
Feel free to reopen it once you have any additional info regarding the error.

**Closed by MikhailTymchukDX** 2016-12-24 19:46 UTC
Labels: needs info, Tabs
