### ISSUE TITLE
AjaxFileUpload won't upload once site is published to IIS7

### ISSUE THREAD

**Issue by ChrisWh71** [DevExpress/AjaxControlToolkit#424] opened 2018-03-15 16:13 UTC
I'm using VS2017 15.6.2 and AjaxControlToolkit 18.1.0
I've tried using the toolkit via both the NuGet package and via the installer.
I've added an Ajaxfileupload to my page. I've added the handler to system.webserver in my web.config, along with the appropriate config section settings for me to set the temp folder. I've tried this with temp folder overridden and without it set so it takes the default. I've also tried this with the UploadHandlerPath set in the asp and without. All the variants have the same result, which is...
When I run the website in VS2017 for IE11 the file uploader works just fine. When I publish it to our IIS server it wont upload any files, just returns the red error message. On our IIS server the website is running in an app pool under the network service account, and I've granted network service full control of the temp folder, but still the file upload fails on the server.
What am I doing wrong?
It's worth mentioning that I'm setting a list of AllowedFileTypes. When I try and upload a file not in this list the AjaxFileUploader reports that that file is not allowed because of the file type. This happens both when running the code in VS and on the server, so it seems as if the file uploader is at least processing the file in some way, just not uploading it (hence my mentioning the permissions on the temp folder).

**Comment by MikhailTymchukDX** [comment] 2018-03-15 16:42
Hi @ChrisWh71 
Please specify the following:
* The error message you see when trying to upload a file
* An IIS application root path
* A page path where AjaxFileUpload is placed
* Screenshots of the Network tab in Chrome Developer tools when you try to upload a file, like this one:
![image](https://user-images.githubusercontent.com/17080984/37477134-f2545c40-2887-11e8-98d7-7eeefcdad5da.png)

**Comment by ChrisWh71** [comment] 2018-03-16 08:06
The IIS application root is 
http://gbvuts17/SalesReview/

The file upload control is on
http://gbvuts17/SalesReview/SalesDetails.aspx

This is what I see on screen...
![ieerror](https://user-images.githubusercontent.com/37413062/37509619-f2316006-28ef-11e8-956c-0b2b0345f45e.JPG)

This is what I see in the console tab in IE11 F12 developers tools
![error](https://user-images.githubusercontent.com/37413062/37509640-1203c536-28f0-11e8-882b-a7aca801e94d.JPG)

This is what I see in the network tab in IE11 F12 developers tools (sorry, don't have Chrome)
![network](https://user-images.githubusercontent.com/37413062/37509652-1bd4e090-28f0-11e8-8916-a4a504861b86.JPG)

This is the asp code. As you can see the file upload control is hidden in a collapsible panel extender
![code](https://user-images.githubusercontent.com/37413062/37509694-482b1196-28f0-11e8-935c-63d28d85477e.JPG)

And here's a screenshot of the relevant pasrts of my web.config
![config](https://user-images.githubusercontent.com/37413062/37509705-5410a07a-28f0-11e8-9127-f9314cbe1789.JPG)

**Comment by ChrisWh71** [comment] 2018-03-19 10:17
I don't get any ASP.NET warnings in the event viewer in this instance. Here's the IIS Logs though. You can see I'm getting an 500.21 (Module not recognized) error.

POST /SalesReview/SalesReview/AjaxFileUploadHandler.axd contextKey={DA8BEDC8-B952-4d5d-8CC2-59FE922E2923}&controlID=ctl00_Content_AjaxFileUpload&fileId=EE9AE02C-2074-887E-912B-8A5D817C4A6E&fileName=Beach.jpg&chunked=false&firstChunk=true 80 ... Mozilla/4.0+(compatible;+MSIE+7.0;+Windows+NT+10.0;+WOW64;+Trident/7.0;+.NET4.0C;+.NET4.0E;+.NET+CLR+2.0.50727;+.NET+CLR+3.0.30729;+.NET+CLR+3.5.30729) 500 21 13 2

Here's the response body from the XMLHttpRequest

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>500 - Internal server error.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>500 - Internal server error.</h2>
  <h3>There is a problem with the resource you are looking for, and it cannot be displayed.</h3>
 </fieldset></div>
</div>
</body>
</html>

**Comment by MikhailTymchukDX** [comment] 2018-03-19 12:03
@ChrisWh71 
Based on the error code you provided, I think [your application runs in Classic application pool mode instead of Integrated mode](https://stackoverflow.com/questions/12069415/iis-7-httphandler-and-http-error-500-21).
Try switching it to the Integrated mode.

If it does not help, temporarily set a custom error mode to off in your application Web.config and check the server response again:
```xml
<configuration>
  <system.web>
    <customErrors mode="Off"/>
  </system.web>
</configuration>
```

**Comment by ChrisWh71** [comment] 2018-03-19 12:41
Our application pool is in Classic mode. Why would that make a difference?

**Comment by MikhailTymchukDX** [comment] 2018-03-19 14:14
Managed handlers, which AjaxFileUploadHandler belongs to, can not be configured to run in IIS classic mode.

This article explains the difference between Classic and Integrated mode for modules and handlers: [IIS 7.0, ASP.NET, pipelines, modules, handlers, and preconditions](https://blogs.msdn.microsoft.com/tmarq/2007/08/30/iis-7-0-asp-net-pipelines-modules-handlers-and-preconditions/)

**Comment by MikhailTymchukDX** [comment] 2018-03-19 14:35
@ChrisWh71 
> When I set IE to break on all errors in the debugger the code stops here...

Would you please provide a sample project that illustrates this issue? I cannot reproduce this behavior locally.

**Comment by ChrisWh71** [comment] 2018-03-19 14:36
Okay, that's interesting, thanks. At least we know now why it's not working and what to do to get it working. It's up to us now to decide what to do next based on the implications of this information. Thanks for all your help.

**Comment by MikhailTymchukDX** [comment] 2018-03-19 16:19
@ChrisWh71 You're welcome!
I consider the issue resolved, so I'm closing it.
Don't hesitate to comment if you have any info.

**Closed by MikhailTymchukDX** 2018-03-19 16:19 UTC
Labels: AjaxFileUpload, needs info
