### ISSUE TITLE
Tab Container showing to right of tabs (IE Compatibility View)

### ISSUE THREAD

**Issue by barryfz** [DevExpress/AjaxControlToolkit#125] opened 2016-05-31 20:12 UTC
I installed using ToolkitInstall.16.1.0.0.  I also pulled a copy of AjaxControlTookit-master.zip to create a sample site on my test server.  How do I tell what version that is using?  

I created an app using the tab control, I did not set any custome css. When I run it in VS 2010 it appears just fine but when I publish to my test web server running IIS the tab content shows to the right of the tabs.  I see this problem discussed when custome css is added but I did not do that.

The same problem occurs when I publish the sample web site to my test server.  I believe the webserver is running IIS v7.5.7600.16385.

**Comment by MikhailTymchukDX** [comment] 2016-06-01 07:59
> How do I tell what version that is using?

When you run a Sample site from within Visual Studio by opening the solution, it references the `AjaxControlToolkit` project.
You can either modify the `AjaxControlToolkit -> Properties -> SharedAssemblyInfo.cs` file to set the required version of the toolkit assembly or remove this reference and install the [AjaxControlToolkit NuGet package](https://www.nuget.org/packages/AjaxControlToolkit/).

> I see this problem discussed when custome css is added but I did not do that.

This is somewhat we did not face before. Would you please provide a sample project that illustrates this issue?

**Comment by barryfz** [comment] 2016-06-01 15:19
I will get back to this. For now  I need to get my app working so will just use buttons instead of tabs.  All I did was take the sample app from AjaxControlTookit-master.zip that I found and publish it to IIS with no changes. I was using VS2010.  That version appears to still be 15.  I tried removing all refs to AjaxControlToolkit and then add via NuGet but I get a not compatible error.  I retried that using VS2013 and didn't get that error but now it doesn't want to run.  The dll I was using in my app (not sample) is v16..  Same problem when published to IIS.  Using VS2010 on that one. Can't upgrade my app just yet and have a deadline.  I will get back to this once I get my app running.

**Comment by barryfz** [comment] 2016-06-01 15:49
I forgot to mention this problem does no happen in Chrome, only IE (V11), even though it looks fine in IE when running from VS.

**Comment by barryfz** [comment] 2016-06-06 19:55
Trying to get back to this. Won't be able to until later this week or early next week. I found an image I had saved showing how it looked when running from IIS.  In VS it looked like expected.  Will report more as soon as I can get to it.
![ajxctltlkitbadtab](https://cloud.githubusercontent.com/assets/6894542/15835677/a14d03b8-2bf6-11e6-8dc2-0e8e3600445a.PNG)

**Comment by MikhailTymchukDX** [comment] 2016-06-07 08:05
Would you please provide a screenshot of a div with the class `ajax__tab_header` in DOM Explorer, so we can see its effective styles?
![image](https://cloud.githubusercontent.com/assets/17080984/15850206/7bc9d4dc-2c9f-11e6-8d37-36665ed9d0e4.png)

**Comment by MikhailTymchukDX** [comment] 2016-06-21 11:54
Since we still haven't received the requested information, I'm closing this issue.
Feel free to reopen it once you have any additional info regarding the error.

**Comment by barryfz** [comment] 2016-07-12 20:04
Sorry it took so long to get back to this, FY change over gets pretty busy here.  I uninstalled and reinstalled AjaxControlToolkit.  I took the sample web site from the install. Opened it with VS2010 and tried to run but got lots of JavaScript errors.  Made another copy and opened with VS2013 runs ok there. Published it from VS2013 to our IIS server.  Get the problem I reported, tab conten showing to the right of the actual tab layout. Uploading the file with DOM explorer view of tab you requested.
![ajaxctrltoolkittabproblem](https://cloud.githubusercontent.com/assets/6894542/16781662/e4358940-4841-11e6-8d0a-fba46c4b3dd7.PNG)

**Comment by AlekseyMartynov** [comment] 2016-07-12 21:02
Thanks. We'll look into it.

**Comment by barryfz** [comment] 2016-07-15 11:54
Thanks

**Comment by MikhailTymchukDX** [comment] 2016-07-20 14:12
@barryfz Would you please go one level down the DOM hierarchy and show us `Content_DemoContent_Tabs_header` div styles and the page screenshot?

**Comment by barryfz** [comment] 2016-07-21 17:02
Does this get you enough?
![ajaxcontroltoolkittabdom2](https://cloud.githubusercontent.com/assets/6894542/17031684/01ca7290-4f3b-11e6-9ce0-103916745ba2.PNG)

**Comment by AlekseyMartynov** [comment] 2016-07-21 17:21
@barryfz 
Thank you for the additional screenshot.
From it, I can see that IE works in IE7 Document Mode, which is a really outdated mode to date.

![01ca7290-4f3b-11e6-9ce0-103916745ba2](https://cloud.githubusercontent.com/assets/4426185/17031922/3ecb0a08-4f7f-11e6-8600-d308567bc9c2.PNG)

Is it on purpose or caused by some misconfiguration?

**Comment by barryfz** [comment] 2016-07-21 18:42
This is an intranet site and the compatibility mode was set for all intranet sites.  I did not set that (as far as I can remember).  Clearing that fixed the problem.  However, I cam going to have to check with our IT Pros to see if this is being set by a GPO or is set for most people to insure compatibility with the old software that runs in intranet here at the Univ of Missouri.  I'll have to get back to you about that.  I do know that when I was in one of the DoIT development groups a few years ago we were using the toolkit and did not see this problem.

**Comment by AlekseyMartynov** [comment] 2016-07-21 21:24
> This is an intranet site and the compatibility mode was set for all intranet sites.

Could you please check if any of suggestions from the following StackOverflow thread help?
http://stackoverflow.com/q/25557299

> a few years ago we were using the toolkit and did not see this problem.

This may be because Tabs have been rewritten several times during 2011-2013:
* http://stephenwalther.com/archive/2011/11/16/ajax-control-toolkit-november-2011-release
* http://stephenwalther.com/archive/2013/12/14/ajax-control-toolkit-december-2013-release

Supporting IE versions as low as 7 doesn't seem practical today. However we'll try to find a workaround or a fix if other solutions don't work.

**Comment by Seteh** [comment] 2016-07-22 09:45
Hi @barryfz.
 
The simplest workaround for that IE7 buggy behavior is to set tab header width to 100%.
Just put this rule to your css file.
```css
.ajax__tab_default .ajax__tab_header { width: 100%; }
```
Let me know if it doesn't help.

**Comment by barryfz** [comment] 2016-08-01 20:15
Thanks, will try it out tomorrow

**Comment by barryfz** [comment] 2016-08-03 20:00
That corrected the problem, thanks.

**Closed** 2016-08-04 08:15 UTC
Labels: Tabs

**Comment by barryfz** [comment] 2016-11-11 18:51
Things still moving slow here at MU.  I pulled the latest code, and am now running it in VS2015.  I was hoping this change would have been put into the tabs.css file but not so far.  Anyway I had the same problem, made the change in the css, but it didn't correct it because the changed code did not show up in the bundled file.  Is bundling something new that has been added?  Or perhaps works diff in VS2015?  Tried lots of things but have only gotten it to pick up the change if in global.asax I make this change:

BundleTable.EnableOptimizations = false; 

Why won't it pick up changes if it is true?

**Comment by MikhailTymchukDX** [comment] 2016-11-14 12:18
Hi @barryfz ,
This likely happens when you modify the debug version of the CSS file (ends with `.css`), but the bundle's CSS file is assembled from minified CSS files (end with `.min.css`), which are unmodified. 

We added two tasks for the gulp ("minify-js" and "minify-css"), which minifies scripts and styles automatically. It is started at project opening: 
![image](https://cloud.githubusercontent.com/assets/17080984/20263963/346a48fc-aa7a-11e6-81dd-7c8d19458212.png)
Do you see this task running?
