### ISSUE TITLE
Opening Modal Popup slow in IE 11

### ISSUE THREAD

**Issue by bcoon0420** [DevExpress/AjaxControlToolkit#126] opened 2016-06-01 21:45 UTC
I have a huge modal popup that contains a lot of sub-forms and multiple toolkit controls including other modal popups extenders.  The modal popup comes up quickly in Chrome, ~1 second.  However, in IE  11 it takes between 6-7 seconds, unacceptably slow.  Profiling the code I see it is spending most of this  time in the disableTab function. Specifically it is making > 11K calls to Array.indexOf which calls Sys._indexOf the same number of times.

Is there anyway to speed this up?  I am not doing anything with tabs in my modal popup.  Can someone explain what this disableTab function is suppose to do?  I don't see any comments in the code.  See attached for profile data.
![disabletapprofile](https://cloud.githubusercontent.com/assets/19697113/15726742/cc0f9c86-280f-11e6-9b86-7414dec633cb.png)

**Comment by AlekseyMartynov** [comment] 2016-06-02 08:49
Thanks for reporting this.

Could you tell us more about the hierarchy and the number of nested controls/extenders residing within the popup?

**Comment by bcoon0420** [comment] 2016-06-02 17:55
Digging into the code a little further I understand how the disableTab works and where the difference lies between IE and Chrome. Here is what disableTab does (starting at line 393 of ModalPopup.js)

First outer for loop - gather all the elements in the popup that are in the tab group into into the tagElementsInPopup array.

Second outer loop - gather all the elements on the page that are in the tab group and compare that list to the elements in tagElementsInPopup using a brute force element comparison (Array.indexOf).  If element is not in the list the element's tab index is turned off.

Array.indexOf calls Sys._indexOf in MicrosoftAjax.js to do the brute force compare. On line 1203 we see

if((typeof (array[i]) !== "undefined") && (array[i] === item)) {

This is where the difference is between IE and Chrome. The object compare (array[i] === item) is much slower in IE than Chrome.

There has got to be a better way than this brute force compare to see if an item is in a list of items.  A dictionary or hash table perhaps.

I did improve the performance somewhat by changing some of my controls from buttons to divs since I didn't need the button functionality.  This cut the number of times Array.indexOf was called to less than 3K, but the popup in IE is still too slow.

**Comment by MikhailTymchukDX** [comment] 2016-06-03 09:02
@bcoon0420 Are the tab groups described above separate tag groups, one of which is placed inside the popup and the other - outside it?
A sample project will help us a lot to understand your layout.

**Comment by bcoon0420** [comment] 2016-06-03 16:42
I have a couple attachments in this post.  The first shows our Project View Editor page with our modal popup Project-View Properties. The seconds shows the a sub-modal popup when the "Edit color palettes...' is clicked.  There are 10-12 other sub-modal popups within the different  menus that you navigate to from the left hand navigation options.

I don't do anything explicit with tag groups.  I just use the default html tabbing behavior.  The ability t
o tab is not important in these modal popups, so if turning tabbing off fixes the performance I would be happy, but I don't think from the code I have seen that would make a difference (I hope I am wrong) .

![pvpshowing](https://cloud.githubusercontent.com/assets/19697113/15786080/da856e76-2977-11e6-9b02-f11168c69b61.png)
![pvpsub-modal](https://cloud.githubusercontent.com/assets/19697113/15786090/e51ae44c-2977-11e6-9b19-530f5724d5a1.png)

**Comment by MikhailTymchukDX** [comment] 2016-06-06 15:38
@bcoon0420 Unfortunately, I can not reproduce the described call sequence using the screenshots you provided.
Would you please provide a sample project, so that we can conduct research?

**Comment by MikhailTymchukDX** [comment] 2016-06-20 09:38
@bcoon0420 Since we still haven't received the requested information, I'm closing this issue.
Feel free to reopen it once you have any additional info regarding the error.

**Closed by MikhailTymchukDX** 2016-06-20 09:38 UTC
Labels: ModalPopupExtender, needs info
