### ISSUE TITLE
Visual Studio Not Found

### ISSUE THREAD

**Issue by Sascha321** [DevExpress/AjaxControlToolkit#402] opened 2017-12-11 17:20 UTC
![01](https://user-images.githubusercontent.com/34453998/33844064-7601ec70-de9f-11e7-8ac5-b1b34d2652ed.JPG)

### The installation method
- [ x ] Installer
- [ ] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
if I want to install the toolkit

### Actual result
the installer breaks off, see picture

### A site deployment method
- [ ] VS development web-server,
- [ ] IIS

**Comment by MikhailTymchukDX** [comment] 2017-12-11 18:01
Hi @Sascha321 
Would you please provide us the log file located in your `%TEMP%` folder?
Its name is `ACTInstaller_<GUID>.log`.

**Comment by Sascha321** [comment] 2017-12-11 18:48
here the logfile
[ACTInstaller_c69f9c09-186d-4653-b546-15da0056e03d.log](https://github.com/DevExpress/AjaxControlToolkit/files/1548994/ACTInstaller_c69f9c09-186d-4653-b546-15da0056e03d.log)

**Comment by MikhailTymchukDX** [comment] 2017-12-11 22:04
@Sascha321 Thank you for providing us with the log!

While we are investigating what causes this issue, you can use [the AjaxControlToolkit NuGet package](https://www.nuget.org/packages/AjaxControlToolkit/), which is installed on a per-project basis.
It lacks toolbox integration, but you can create the markup manually.

To get some help with that, please check [the Sample site source code](https://github.com/DevExpress/AjaxControlToolkit/tree/master/AjaxControlToolkit.SampleSite) and [Sample site online demo](https://ajaxcontroltoolkit.devexpress.com/).
Also, don't forget to check [the control reference](https://github.com/DevExpress/AjaxControlToolkit/wiki#reference-v1711) so you can use all the control settings.

**Comment by MikhailTymchukDX** [comment] 2017-12-12 10:52
Hi @Sascha321 
According to your log, Visual Studio installation is in incomplete state:
```
2017-12-11 07:45:59 | INFO  | EnvironmentInfo.LogInstanceInfo          | VisualStudio detected, InstanceId: 63fd40d4 (Incomplete)) 
```
While that flag does not say much about the cause of this state, I suggest that you reboot or even reinstall your instance of Visual Studio to put it into the correct state.

Please inform us of your results.

**Comment by Sascha321** [comment] 2017-12-12 17:05
Thank you, I have reinstalled Visual Studio. After that, I was also able to install the Ajax Toolkit.

**Comment by MikhailTymchukDX** [comment] 2017-12-12 17:21
Glad to hear it!
I consider this issue resolved, so I'm closing it.

**Closed by MikhailTymchukDX** 2017-12-12 17:21 UTC
Labels: needs info

**Comment by kajbonfils** [comment] 2018-01-03 11:41
Getting the same issue. Wouldn't it be better to fix the installer not to break because of this? 

I would really like to be able to install the toolkit on a visual studio that is running perfectly. It will cost me close to a day to do a full uninstall/reinstall of VS2017 - including plugins, settings etc.

Anyways... I think I have a different cause for the failure. In my case, it seems that its because its looking in the buildtools folder, instead of in the enterprise folder... (I have both buildtools and VS 2017 installed to test various devOps scripts)

-Kaj

018-01-03 12:33:15 | INFO  | App.Application_Startup                  | Installer started 
2018-01-03 12:33:15 | INFO  |                                              VSIX name: ASP.NET AJAX Control Toolkit 
2018-01-03 12:33:15 | INFO  |                                              VSIX id: e79bade7-6755-466f-9788-3d8243bdcc5f 
2018-01-03 12:33:15 | INFO  |                                              VSIX version: 17.1.1.0 
2018-01-03 12:33:15 | INFO  | App.Application_Startup                  | Process Info 
2018-01-03 12:33:15 | INFO  |                                              OS: Microsoft Windows NT 6.2.9200.0 
2018-01-03 12:33:15 | INFO  |                                              Is 64bit: True 
2018-01-03 12:33:15 | INFO  |                                              Is admin: False 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.CheckLegacyVersionIsInstalled | VisualStudio 2010 not detected 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.CheckLegacyVersionIsInstalled | VisualStudio 2012 not detected 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.CheckLegacyVersionIsInstalled | VisualStudio 2013 not detected 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.CheckLegacyVersionIsInstalled | VisualStudio 2015 not detected 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | VisualStudio detected, InstanceId: bc7e69f4 (Complete)) 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | InstallationVersion: 15.4.27004.2005 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | InstallationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | ProductPath: Common7\Tools\LaunchDevCmd.bat 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.PrintWorkloads           | Microsoft.VisualStudio.Workload.MSBuildTools 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.PrintWorkloads           | Microsoft.VisualStudio.Workload.WebBuildTools 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | VisualStudio 2017 Microsoft.VisualStudio.Product.BuildTools detected 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | VisualStudio detected, InstanceId: de55e490 (Complete)) 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | InstallationVersion: 15.5.27130.2010 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | InstallationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | ProductPath: Common7\IDE\devenv.exe 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.PrintWorkloads           | Microsoft.VisualStudio.Workload.CoreEditor 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.PrintWorkloads           | Microsoft.VisualStudio.Workload.Data 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.PrintWorkloads           | Microsoft.VisualStudio.Workload.ManagedDesktop 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.PrintWorkloads           | Microsoft.VisualStudio.Workload.NetCoreTools 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.PrintWorkloads           | Microsoft.VisualStudio.Workload.VisualStudioExtension 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.LogInstanceInfo          | VisualStudio 2017 Microsoft.VisualStudio.Product.Enterprise detected 
2018-01-03 12:33:15 | ERROR | RegistryNativeMethods.RegLoadAppKey      | Failed during RegLoadAppKey for file C:\Users\x1tb\AppData\Local\Microsoft\VisualStudio\15.0_bc7e69f4\privateregistry.bin. Error code: 3 
2018-01-03 12:33:15 | TRACE | EnvironmentInfo.GetInstallerPath         | C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VSIXInstaller.exe does not exist 
2018-01-03 12:33:15 | TRACE | EnvironmentInfo.GetInstallerPath         | C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VSIXInstaller.exe does not exist 
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.GetEnvironmentInfo       |  
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.GetEnvironmentInfo       |  
2018-01-03 12:33:15 | INFO  | EnvironmentInfo.GetEnvironmentInfo       | Vsix installer path is  
2018-01-03 12:33:15 | WARN  | MainWindow..ctor                         | No Visual Studio instance installed. Installer terminated

**Comment by kajbonfils** [comment] 2018-01-03 11:49
Uninstalling the MSBuildTools did the job. Now ACT is installing, then I can reinstall the build tools afterwards.

-Kaj
