### ISSUE TITLE
AJAX Masked editor not working in chrome android

### ISSUE THREAD

**Issue by krajchn** [DevExpress/AjaxControlToolkit#356] opened 2017-07-03 12:59 UTC
### The installation method
- NuGet package

### Minimal steps to reproduce the bug
1. Open chrome in android and navigate to the following url
https://ajaxcontroltoolkit.devexpress.com/MaskedEdit/MaskedEdit.aspx

2. Enter random numbers in Enter Date text field.

### Actual result
1. Text fields allows me to enter more than 8 characters
2. Masking is not applied as I type.
![screenshot_20170703-182821](https://user-images.githubusercontent.com/15866983/27793908-80209e46-601d-11e7-8b72-91ad0723a2c0.png)

### Expected result
1. It should allow only 8 characters.
2. Masking should be maintained while typing.

### Browser(s) used
Android Chrome version 58.0.3029.83

**Comment by MikhailTymchukDX** [comment] 2017-07-04 13:05
Hi @krajchn
We cannot reproduce this behavior in our environment.

Would you please provide us the following info:
1. Where do you set the cursor inside the textbox before starting to type?
2. What buttons do you press?
3. What is your Android version?
4. What is your system locale?

A short video that illustrates the issue would be very helpful.

**Comment by MikhailTymchukDX** [comment] 2017-07-17 10:05
Since we still haven't received the requested information, I'm closing this issue.
Feel free to reopen it once you have any additional info regarding the error.

**Closed by MikhailTymchukDX** 2017-07-17 10:05 UTC
Labels: MaskedEditExtender, needs info

**Comment by Eyal-M** [comment] 2019-03-30 00:39
This problem is still happening!
krajchn described it perfectly.
You can see it happening with the regular MaskEdit demo page.
I checked it with my Samsung J5 smartphone and with my Xiaomi smartphone (bought this year).
There are NO problem with this page on any desktop - works OK on all Windows desktop that i have.
All smartphones and desktops running latest Chrome browser.
