### ISSUE TITLE
AjaxControlToolkit v17.1.1 Drag and Drop not working on Edge and Firefox

### ISSUE THREAD

**Issue by edwardcampbellprojects** [DevExpress/AjaxControlToolkit#362] opened 2017-07-06 21:59 UTC
### The installation method
- [x ] Installer
- [ x] NuGet package  (tried both)
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug  
using VS2015 Professional Update 3:

Download and install AjaxControlToolkit 17.1.1  (ACT, hereafter)
Install ACT controls into the toolbox as instructed here: 
  https://www.aspsnippets.com/Articles/Install-AJAX-Control-Toolkit-in-Visual-Studio-ToolBox.aspx 
Build the example prototype as instructed here:
  https://www.aspsnippets.com/Articles/Multiple-files-upload-with-Drag-and-Drop-and-Progress-bar-
  using-ASPNet-AJAX-AjaxFileUpload-control.aspx 

### Actual result
Drag and drop does not show 'Drop cursor' in FF or Edge and nothing happens on drop

### Expected result
Drag and drop does show 'Drop cursor' in Chrome and dropped file appears in list and upload directory

### Browser(s) used
Chrome Version 59.0.3071.115 (Official Build) (32-bit), works as expected here
Edge: IE v 11.0.9600.18697
FireFox: v54.0.1

### A site deployment method
- [x ] VS development web-server,
- [x ] IIS tried both, same result

see the project cited above  and my prototype files are attached below

[AjaxControlToolkit_17-Test-03.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1129395/AjaxControlToolkit_17-Test-03.zip)

 attached below

**Comment by MikhailTymchukDX** [comment] 2017-07-07 09:44
Hi @edwardcampbellprojects 
I do not completely understand your scenario.
Everything works fine when I remove a script that hides the drop zone from your sample project.

**Comment by edwardcampbellprojects** [comment] 2017-07-07 15:20
Mikhail,

Thank you for your quick response.  I have attached 3 .mp4 files that show
the problem I am having.

From experimenting with other versions, it appears that the dragover event
handler is not loading.  I am not a JS expert and am just thrashing about
trying to find a set of conditions that will work reliably.

I will try to manually register an event handler and see if that changes
anything.

Any thoughts you have will be appreciated.

Thanks again,

Edward Campbell

**Comment by MikhailTymchukDX** [comment] 2017-07-07 15:50
Hi @edwardcampbellprojects 
Attaching a file does not work when you reply via e-mail.
Please attach it via web site.

**Comment by edwardcampbellprojects** [comment] 2017-07-07 18:28
Attached as requested: zipped .mp4 files showing the failure under same VS 2015 Update 3 and other browsers cited in original submission.
[AjaxControlToolkit-DnDProblemMP4.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1131958/AjaxControlToolkit-DnDProblemMP4.zip)

**Comment by MikhailTymchukDX** [comment] 2017-07-10 09:12
@edwardcampbellprojects These videos show the original projects's behavior, but it seems the project is misconfigured.

I attached the modified version of your example: [DragDropTest.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1134954/DragDropTest.zip)

Please check if it works correctly and inform us of the results.

**Comment by edwardcampbellprojects** [comment] 2017-07-10 17:22
Mikhail,

Thanks very much for your reply.  I have been taking care of urgent matters
this morning but will be working on this today.

I will keep you informed of my progress.

Ted Campbell

**Comment by edwardcampbellprojects** [comment] 2017-07-11 14:20
Hi Mikhail,

I regret to have to say that there is no change in drag and drop operation
when using the example you sent.  Chrome drag and drop works, FireFox and
IE do not.

Any further advice or guidance is appreciated.

Ted Campbell

**Comment by MikhailTymchukDX** [comment] 2017-07-11 14:54
@edwardcampbellprojects 
Does drag and drop work in Firefox and IE on [our sample site](https://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx)?

**Comment by edwardcampbellprojects** [comment] 2017-07-11 16:08
Mikhail,

Interesting question.

Trying on your sample site:
https://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx


IE
DnD and upload works on IE (11.0.9600.18697) Update Versions 11.0.43
(KB4021558).  Upload fails intermittently with .jpg files but that is a
separate problem.

FireFox
DnD does not work on Firefox, v 54.0.1 (32-bit), never showing the drop
cursor.

Chrome
DnD and upload works on Chrome Version 59.0.3071.115 (Official Build)
(32-bit).  Upload also fails intermittently with .jpg files

Thanks for your continued efforts.

Ted Campbell

On Tue, Jul 11, 2017 at 10:54 AM, MikhailTymchukDX <notifications@github.com

**Comment by MikhailTymchukDX** [comment] 2017-07-12 11:21
@edwardcampbellprojects 
Thank you for the response.
It seems the problem is with your environment.

Let's focus on Firefox. Please provide the following info:
1. An OS version.
2. A list of plugins installed to Firefox.
3. HTML code of [the sample page](https://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx) - open it, press Ctrl+U, then provide a content of a page shown.
4. Errors in a browser's console, if any.

**Comment by edwardcampbellprojects** [comment] 2017-07-12 20:49
Mikhail,

My client supplied laptop was rebooted today.  When I tried to reproduce
the FireFox DnD errors on the DevEx demo site, I could not.  There are no
errors and DnD works as expected.  I have been assigned another project
that supercedes the one for which I was considering AjaxControlToolkit.
This project will be activated again once the more pressing assignment is
completed.

I do not know what could have changed.  There have been no software changes
that I am aware of.

My apologies for taking your time without being able to reach a resolution.

I will let you know when the DnD project resumes.

Ted Campbell

**Comment by MikhailTymchukDX** [comment] 2017-07-13 09:04
@edwardcampbellprojects 
Thank you for your reply. As the problem is solved, I'm closing this issue.
Feel free to reopen it if you have any further questions.

**Closed by MikhailTymchukDX** 2017-07-13 09:04 UTC
Labels: AjaxFileUpload, needs info
