### ISSUE TITLE
How to use TabContainer in SharePoint 2013

### ISSUE THREAD

**Issue by rusaym** [DevExpress/AjaxControlToolkit#418] opened 2018-03-01 14:55 UTC
Hey!
When I place a html table in tabPanel  in SharePoint 2013,  for some reason the table showing out of the tabPanel. 

```
<%@ Assembly Name="$SharePoint.Project.AssemblyFullName$" %>
<%@ Assembly Name="Microsoft.Web.CommandUI, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<%@ Register TagPrefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<%@ Register TagPrefix="Utilities" Namespace="Microsoft.SharePoint.Utilities" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<%@ Register TagPrefix="asp" Namespace="System.Web.UI" Assembly="System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" %>
<%@ Import Namespace="Microsoft.SharePoint" %>
<%@ Register TagPrefix="WebPartPages" Namespace="Microsoft.SharePoint.WebPartPages" Assembly="Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="DocInfo.ascx.cs" Inherits="RSIT.OfficeWork.ControlTemplates.RSIT.OfficeWork.DocInfo" %>
<%@ Register Assembly="AjaxControlToolkit, Version=17.1.1.0, Culture=neutral, PublicKeyToken=28f01b0e84b6d53e" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>


<ajaxToolkit:TabContainer runat="server" ActiveTabIndex="0" Width="100%">
    <ajaxToolkit:TabPanel runat="server" HeaderText="header1" ID="TabPanel1">
        <ContentTemplate>
            <table style="width: 100%;">
                <tr>
                    <td>1</td>
                    <td>sdf</td>
                    <td>66</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>scxv</td>
                    <td>55</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>cvbvnv</td>
                    <td>44</td>
                </tr>
            </table>
        </ContentTemplate>
    
</ajaxToolkit:TabPanel>


    <ajaxToolkit:TabPanel ID="TabPanel2" runat="server" HeaderText="header 2">
        <ContentTemplate>
            1        
        </ContentTemplate>    
    </ajaxToolkit:TabPanel>
</ajaxToolkit:TabContainer>
```
![1](https://user-images.githubusercontent.com/17137916/36851133-91e71208-1d79-11e8-9d93-4bad41e74934.png)

**Comment by MikhailTymchukDX** [comment] 2018-03-02 07:57
Hi @rusaym 
I can not reproduce this behavior using the markup you provided.
Would you please provide a sample project that illustrates this issue?

**Comment by rusaym** [comment] 2018-03-02 12:57
[TabContainer_.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1775125/TabContainer_.zip)

**Comment by rusaym** [comment] 2018-03-02 13:05
You have to change "NewFormTemplateName", "DisplayFormTemplateName" and "EditFormTemplateName" to "CustomForm" on some of your content type, using Sharepoint Manager

**Comment by MikhailTymchukDX** [comment] 2018-03-05 17:33
Hi @rusaym 
This behavior is caused by [this change](https://github.com/DevExpress/AjaxControlToolkit/commit/ca70a524aeccd30d23fed1b0d95830be1d635ef9) that allows displaying several tab header rows.
It breaks page layout in some specific cases.

To negate this effect, add this style to your control's markup:
```css
<style>
    .ajax__tab_default .ajax__tab {
        display: inline !important;
        float: none !important;        
    }

    .ajax__tab_xp .ajax__tab_header:before, .ajax__tab_xp .ajax__tab_header:after {
        display: inline !important;
    }

    .ajax__tab_xp .ajax__tab_header {
        height: 21 px;
    }
</style>
```

Please inform us of your result.

**Comment by rusaym** [comment] 2018-03-06 08:14
It hasn't worked out for me, maybe I do something wrong. Did you reproduce this problem using my project? If you did, can you upload corrected project?

**Comment by MikhailTymchukDX** [comment] 2018-03-06 08:24
Sure: [TabContainer_2.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1784089/TabContainer_2.zip)

**Comment by rusaym** [comment] 2018-03-06 09:37
There is no problem, if you place "Info.ascx" control in application page, but I use "Info.ascx" control in another control ("MyControl.ascx" with renderingtemplete id="CustomForm"), that is rendering template of my custom content type. So, adding styles doesn't work in this situation.
![image](https://user-images.githubusercontent.com/17137916/37024560-3fbf4b66-213a-11e8-9973-c96466d8a34a.png)
To reproduce this problem, you have to set "NewFormTemplateName", "DisplayFormTemplateName" and "EditFormTemplateName" values to "CustomForm" on one of your content type, using Sharepoint Manager.
![image](https://user-images.githubusercontent.com/17137916/37024798-ebfff27c-213a-11e8-9caf-bbbe10fb0f71.png)
Than try to create new item in list.
![image](https://user-images.githubusercontent.com/17137916/37024839-0804ffb2-213b-11e8-8140-bb4154ca25f5.png)

**Comment by MikhailTymchukDX** [comment] 2018-03-06 12:19
Hi @rusaym 
I have managed to reproduce this behavior.

The reason for this is that Sharepoint renders Tab contents incorrectly.

It places TabContainer before the markup block where it is defined, and keeps the rest in the correct place:

![image](https://user-images.githubusercontent.com/17080984/37031231-0f986df4-214f-11e8-838b-12c4d5ae7eac.png)

It looks like this transformations takes place on the client side, because if we check the page source code, we'll see that the control's markup is correct:
```html
<table class="ms-formtable" style="margin-top: 8px;" border="0" cellpadding="0" cellspacing="0" width="100%">
    <style>
        .ajax__tab_default .ajax__tab {
            display: inline !important;
            float: none !important;
        }

        .ajax__tab_xp .ajax__tab_header:before, .ajax__tab_xp .ajax__tab_header:after {
            display: inline !important;
        }

        .ajax__tab_xp .ajax__tab_header {
            height: 21px;
        }
    </style>
    <div id="ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00" style="width:100%;visibility:hidden;">
        <div id="ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00_header" class="ajax__tab_header">
            <span id="ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00_TabPanel1_tab" class="ajax__tab"><span class="ajax__tab_outer"><span class="ajax__tab_inner"><a class="ajax__tab_tab" id="__tab_ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00_TabPanel1" href="#" style="text-decoration:none;"><span>header1</span></a></span></span></span><span id="ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00_TabPanel2_tab" class="ajax__tab"><span class="ajax__tab_outer"><span class="ajax__tab_inner"><a class="ajax__tab_tab" id="__tab_ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00_TabPanel2" href="#" style="text-decoration:none;"><span>header 2</span></a></span></span></span>
        </div><div id="ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00_body" class="ajax__tab_body" style="display:block;">
            <div id="ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00_TabPanel1" class="ajax__tab_panel">

                <table style="width: 100%;">
                    <tr>
                        <td>1</td>
                        <td>sdf</td>
                        <td>66</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>scxv</td>
                        <td>55</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>cvbvnv</td>
                        <td>44</td>
                    </tr>
                </table>

            </div><div id="ctl00_ctl33_g_94cdb0ac_6713_454d_b103_21f3052888e8_ctl00_Info_ctl00_TabPanel2" class="ajax__tab_panel" style="display:none;visibility:hidden;">

                1

            </div>
        </div>
    </div>

...
```

I'm closing this issue, because we did not detect any bug in the AJAX Control Toolkit.
Feel free to comment if you need any assistance.

**Closed by MikhailTymchukDX** 2018-03-06 12:19 UTC
Labels: Tabs

**Comment by rusaym** [comment] 2018-03-06 12:47
May be you have any suggestion to resolve this problem? 
By the way, if place html controls or text without table, the form renders correct.

![image](https://user-images.githubusercontent.com/17137916/37033054-9e757a66-2155-11e8-8d52-ce2d8fb36aaf.png)

**Comment by MikhailTymchukDX** [comment] 2018-03-06 15:09
@rusaym 
You can arrange DOM elements in the correct order using a code like the following:
```html
<script  
	src="https://code.jquery.com/jquery-2.2.4.min.js"
	integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
	crossorigin="anonymous"></script>

<script type="text/javascript">
	$(document).ready(function () {
		var sharepointContainer = $(".ms-formtable");
		var panel1Content = sharepointContainer.next();
		var panel2Content = panel1Content.next();
		var tabPanels = $(".ajax__tab_panel");
		var tabContainer = $(".ajax__tab_container");
		var tabBody = $(".ajax__tab_body");
		panel1Content.detach().appendTo(tabPanels[0]);
		panel2Content.detach().appendTo(tabPanels[1]);
		tabPanels.detach().appendTo(tabBody);
		tabContainer.detach().appendTo(sharepointContainer);
	});
</script>
```

However, I cannot guarantee that this approach will work in more complex case.

**Comment by rusaym** [comment] 2018-03-07 10:59
@MikhailTymchukDX, Thank you!
