### ISSUE TITLE
HtmlEditorExtender drops spaces on postback of data pasted from word

### ISSUE THREAD

**Issue by jesanfafon** [DevExpress/AjaxControlToolkit#333] opened 2017-05-17 15:30 UTC
### The installation method
- [ ] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Minimal steps to reproduce the bug
```html
<asp:TextBox ID="txtMessage" runat="server" CssClass="" Height="150px" />
<cc2:HtmlEditorExtender ID="txtMessageExt" TargetControlID="txtMessage" runat="server" DisplayPreviewTab="true" DisplaySourceTab="true"  />
```

Consider a page with that arrangement of TextBox and HtmlEditorExtender

Pasting the following text typed into Word:
```
Matthew and Kirbie,
Congratulations on the successful agreement you have secured to sell your home.
My name is Jamie Dickson with Berkshire Hathaway Homes Services – The Preferred Realty. I am the transaction coordinator for Joanne Bates and will be assisting in managing your transaction file. As you will be receiving documents, email communication and information from me occasionally at Joanne’s request, I wanted to take this opportunity to introduce myself. 
You will be receiving copies of all of your listing contracts and additional documents by email, as well as a link to your documents. Those will be sent in a separate email.
I am looking forward to participating in providing you with quality service.
```

### Actual result
On postback, the data is bungled to:
```
Matthew and Kirbie,

Congratulationson the successful agreement you have secured to sell your home.

Myname is Jamie Dickson with BerkshireHathaway HomesServices - The Preferred Realty.  I am the transactioncoordinator for Joanne Bates and will be assisting in managingyour transaction file.  As you will be receiving documents,email communication and information from me occasionally at Joanne’s request, I wanted to take this opportunity tointroduce myself.  

Youwill be receiving copies of all of your listing contracts and additionaldocuments by email, as well as a link to your documents.  Those will be sent in a separate email.

I amlooking forward to participating in providing you with quality service.
```

### Expected result

The text to not drop spaces pasted into the editor

### Browser(s) used
Chrome 58, Chrome 60, Internet Explorer 11

### A site deployment method
- [x] VS development web-server,
- [ ] IIS

**Comment by jesanfafon** [comment] 2017-05-17 15:32
The same issue is present with `HtmlEditor` starting in at least version 8 of the Nuget package.

**Comment by MikhailTymchukDX** [comment] 2017-05-22 12:15
Hi @jesanfafon
Do you see newlines before the postback, when you just have pasted the text?

**Comment by jesanfafon** [comment] 2017-05-22 15:43
No, I do not.
Here's the exact value upon post-back:
```<p>Matthew and Kirbie,</p><p>Congratulations on the successful agreement you have securedto sell your home.</p><p>My name is Jamie Dickson with Berkshire Hathaway HomeServices – The Preferred Realty. I am the transaction coordinator for JoanneBates and will be assisting in managing your transaction file. As you will bereceiving documents, email communications and information from me occasionallyat Joanne’s request, I wanted to take this opportunity to introduce myself.</p><p>You will be receiving copies of all of your listingcontracts and additional documents my email, as well as a link to yourdocuments. Those will be sent in a separate email.</p><p>I am looking forward to participating in providing you with qualityservice.</p>```

**Comment by jesanfafon** [comment] 2017-05-22 21:59
Seems to me from some minor investigation, that it might have something to do with normalizing line endings.

**Comment by MikhailTymchukDX** [comment] 2017-05-23 18:13
@jesanfafon I can not reproduce this issue so that HtmlEditorExtender behaves exactly as your case.
To narrow down the problem, please check my steps:

1. I copy sample text into Word 2016:
![image](https://cloud.githubusercontent.com/assets/17080984/26368451/552fc27c-3ffa-11e7-9eb7-4bedc5d141e9.png)

    Please note that Word creates new paragraphs on each new line which can easily be seen.

2. I copy this text from Word into a content editable div I created at [jsfiddle](https://jsfiddle.net/j2g3pmqs/5/) using Chrome 58:
![image](https://cloud.githubusercontent.com/assets/17080984/26368226/aded99da-3ff9-11e7-84c9-a8272a000594.png)

    HtmlEditorExtender uses div with a `contenteditable` attribute set to "true", so there is no difference.
As you can see, Word paragraphs are converted into HTML paragraphs, as expected.

3. A similar result occurs when I paste the text using IE:
![image](https://cloud.githubusercontent.com/assets/17080984/26368719/1c5212e2-3ffb-11e7-86ca-069b80de97b4.png)

4. Now I paste same text as a plain text using Chrome:
![image](https://cloud.githubusercontent.com/assets/17080984/26368405/34b97d44-3ffa-11e7-84e7-8c55749d9b5f.png)

5. The result is different:
![image](https://cloud.githubusercontent.com/assets/17080984/26368567/ad35b9a4-3ffa-11e7-8857-5a204d93588e.png)

    As you can see, there is no HTML paragraph. Text is wrapped into divs instead.

So far, it seems to be a browser-dependent rendering issue which affects contenteditable divs.
Please inform us of your results with fiddle, so we can investigate it further.

**Comment by jesanfafon** [comment] 2017-05-24 16:36
Yes, that all makes sense! To be clear, the issue I'm having isn't that the text looks wrong in the editor after pasting (to the contrary, it looks perfect), it's that the data being posted by the control has the spaces dropped:

![image](https://cloud.githubusercontent.com/assets/3580971/26414535/57c1fd74-4064-11e7-8f1f-eb85fc4ffef3.png)

**Comment by MikhailTymchukDX** [comment] 2017-05-25 13:49
@jesanfafon I am still not sure what dropped spaces you mentioned.
Would you please attach a sample Word file to the issue and indicate what parts of this document are affected?

**Comment by jesanfafon** [comment] 2017-05-25 20:41
Sure can. 

If you look at the image I attached, you'll see that there are periodically spaces missing between words that have spaces between them in the word document (and on screen in the actual control).

If you inspect the data being posted back from the control, you will see that the value in the textarea has spaces missing compared to the word document.

`<p>Matthew and Kirbie,</p><p>Congratulations on the successful agreement you have securedto sell your home.</p><p>My name is Jamie Dickson with Berkshire Hathaway HomeServices – The Preferred Realty. I am the transaction coordinator for JoanneBates and will be assisting in managing your transaction file. As you will bereceiving documents, email communications and information from me occasionallyat Joanne’s request, I wanted to take this opportunity to introduce myself.</p><p>You will be receiving copies of all of your listingcontracts and additional documents my email, as well as a link to yourdocuments. Those will be sent in a separate email.</p><p>I am looking forward to participating in providing you with qualityservice.</p>`

[CopySource.docx](https://github.com/DevExpress/AjaxControlToolkit/files/1030185/CopySource.docx)

**Comment by jesanfafon** [comment] 2017-05-26 14:38
I was looking into this a bit more yesterday, and the value in the backing input has the spaces dropped immediately after pasting the word doc content into the editable div.

**Comment by MikhailTymchukDX** [comment] 2017-05-26 15:45
@jesanfafonI I see that the space between the `listing contracts` disappeared, but cannot reproduce this issue.
Would you please record a video to illustrate it? You can use the [Jing too](https://www.techsmith.com/jing.html)l for this.

**Comment by MikhailTymchukDX** [comment] 2017-06-09 08:52
Since we still haven't received the requested information, I'm closing this issue.
Feel free to reopen it once you have any additional info regarding the error.

**Closed by MikhailTymchukDX** 2017-06-09 08:52 UTC
Labels: HtmlEditorExtender, needs info

**Comment by freefishgolden** [comment] 2017-07-07 17:12
thanks




_Sent from my HUAWEI NXT-AL10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NXTwoThou** [comment] 2020-05-08 19:10
> Since we still haven't received the requested information, I'm closing this issue.
> Feel free to reopen it once you have any additional info regarding the error.

I just ran into this issue.  I put together a quicky page for my boss to send out mailings for his golfing group.  He sent me a word doc, I copy+pasted it into an HTMLEditor  I was shocked when I got an angry "what did you do to my text?" that I'm trying to track down.

I opened this with Word 2007

[PropertyOwnersLetter3.docx](https://github.com/DevExpress/AjaxControlToolkit/files/4600932/PropertyOwnersLetter3.docx)

I did a "Select All" and copy and then did a paste into my 

```
<asp:TextBox ID="HTMLEdit" runat="server" Height="600" Width="100%" />
                                <ajaxToolkit:HtmlEditorExtender ID="hHTMLEdit" runat="server" TargetControlID="HTMLEdit" EnableSanitization="false" DisplaySourceTab="true" />
```
And visually, it looks like this(added red box to point out where my first error eventually comes in)

![Untitled](https://user-images.githubusercontent.com/15003605/81438006-a66fef00-9131-11ea-913d-8c6de79fca8b.png)

Switching to source view it still looks fine

![Untitled2](https://user-images.githubusercontent.com/15003605/81438245-0bc3e000-9132-11ea-80ec-a54b4c2c0e68.png)

If I open up developer tools, I can see some strangeness, but, you'll see in the word doc there's no newline, only a space(which is how it renders onscreen)

![Untitled3](https://user-images.githubusercontent.com/15003605/81438707-cc49c380-9132-11ea-9aa8-0a434446c716.png)

And does not come over correctly on postback

![Untitled4](https://user-images.githubusercontent.com/15003605/81438897-22b70200-9133-11ea-9518-8d7755783c9a.png)

That was with Edge(New) 84.0.508.0

Same results with Edge(Old) 44.19624.1000.0

![Untitled5](https://user-images.githubusercontent.com/15003605/81439174-935e1e80-9133-11ea-878d-fd6ada5477ce.png)

FireFox 78.0.a1 looks a bit different

![Untitled6](https://user-images.githubusercontent.com/15003605/81439429-fcde2d00-9133-11ea-8113-3136a6bacc63.png)

But ends up destroying the space between the "to" and "my" just like the other two browsers(sorry, since so much header was retained, had to paste into notepad to see).

![Untitled7](https://user-images.githubusercontent.com/15003605/81439769-7fff8300-9134-11ea-9b74-e9e8d76e2da1.png)

Meanwhile, I paste into notepad, and it's fine

![Untitled8](https://user-images.githubusercontent.com/15003605/81439890-bc32e380-9134-11ea-8abc-43e44deb04e9.png)

If I dump a second multiline textbox, it's also fine

![Untitled9](https://user-images.githubusercontent.com/15003605/81440358-8b06e300-9135-11ea-831e-cfe061538a55.png)

![Untitled10](https://user-images.githubusercontent.com/15003605/81440368-8e9a6a00-9135-11ea-8718-37b605a2edc8.png)

So is this a windows pasting problem?
