### ISSUE TITLE
Multiple file selection does not work if mode="server" in ajaxfileupload

### ISSUE THREAD

**Issue by rshahLS** [DevExpress/AjaxControlToolkit#423] opened 2018-03-14 19:58 UTC

**Comment by MikhailTymchukDX** [comment] 2018-03-15 10:13
Hi @rshahLS 
I successfully selected multiple files using Mode="Server" and uploaded them:

![image](https://user-images.githubusercontent.com/17080984/37456738-2275feec-2851-11e8-9727-b6f72c43bb07.png)

![image](https://user-images.githubusercontent.com/17080984/37456788-3f3a0eb0-2851-11e8-9074-f3644747ef1a.png)

Please check my sample project: [AjaxFileUploadMultipleSelection.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1814860/AjaxFileUploadMultipleSelection.zip)
If it does not reflect your case, please update it and attach the modified version to this thread.

**Comment by rshahLS** [comment] 2018-03-15 13:29
Tried running your project but I am unable to select multiple files at once using ctrl+select

**Comment by MikhailTymchukDX** [comment] 2018-03-15 21:15
Hi @rshahLS 
The `AjaxFileUploadMode` setting description is confusing, so I'll explain what really happens when you set it.

If you set it to `Auto` or `Client`, AjaxFileUpload will use HTML 5 for file uploading, if the browser supports it. Otherwise, it will use HTML 4.
The key difference here is that [input does not have the `multiple` attribute in HTML 4](https://www.w3schools.com/tags/att_input_multiple.asp). So, AjaxControlToolkit will not render it and will not try to process multiple file selection.

If you set `AjaxFileUploadMode` to `Server`, AjaxFileUpload [will force HTML 4-like processing](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/Scripts/AjaxFileUpload.js#L1085). That means it will use input without `multiple` attribute and this attribute will not affect control's logic even if we add it.

So, if you set `AjaxFileUploadMode` to `Server`, you are limited to single file selection.
I recommend omit this setting, so the control will use `Auto` by default.

I also would like to thank you, that you revealed this inconsistency in our documentation.
I created [new issue for documentation update](https://github.com/DevExpress/AjaxControlToolkit/issues/425), so you can track its progress.

As I mentioned above, this control's behavior is intended, so I marked this issue as `by design` and closed it.
If you have any info on this, please don't hesitate to post a new comment.

**Closed by MikhailTymchukDX** 2018-03-15 21:15 UTC
Labels: AjaxFileUpload, by design
