### ISSUE TITLE
Images with unicode chars in file name not show after upload

### ISSUE THREAD

**Issue by jsanant1** [DevExpress/AjaxControlToolkit#254] opened 2016-11-04 16:56 UTC
Hi, I have problems when I try to upload image files throug AjaxFileUpload with unicode chars in file name like 3º Vista general.jpg, the file upload but after, the file looks like corrupt because i can not open it.

If I change the name and remove this unicode chars then the upload is correct and image show well without any problems.

**Comment by MikhailTymchukDX** [comment] 2016-11-07 08:32
Hi @jsanant1,
This issue was fixed in v15.1.3: https://ajaxcontroltoolkit.codeplex.com/workitem/27655
Would you please clarify what version of the AJAX Control Toolkit you are using?

**Comment by jsanant1** [comment] 2016-11-07 09:34
Hi, yes, i am using an older version but the problem is that when I try to upload this types of images files at the demo page https://ajaxcontroltoolkit.devexpress.com/AjaxFileUpload/AjaxFileUpload.aspx I think the problem persist because the image not show. I would not like to update my project with the new version and make several changes on it if the problem persist.

**Comment by jsanant1** [comment] 2016-11-07 10:11
Exist anther way to fix this problem without installing the new Ajax control toolkit version?

**Comment by MikhailTymchukDX** [comment] 2016-11-07 11:31
I cannot reproduce this issue on a Sample Site.
Would you please attach a file that illustrates the problem?

>Exist anther way to fix this problem without installing the new Ajax control toolkit version?

No, upgrading to the v15.1.3 or above is the only way to upload such files.

**Comment by jsanant1** [comment] 2016-11-08 09:19
Hi, Thank you very much for your help, I hove solved the problem rewriting the Sys.Extended.UI.AjaxFileUpload.ProcessorHtml5 method and now works fine.

**Closed** 2016-11-08 09:27 UTC
Labels: AjaxFileUpload
